name: Security Scan - OWASP ZAP ⚡     # More info = https://www.zaproxy.org/docs/docker/baseline-scan/
run-name: 'Zapoxy Scan #${{ github.run_number }}'
on: 
  workflow_dispatch:              # Enables manual run option
  schedule:
  - cron:  '0 4 * * 0'            # Sunday at 4AM

jobs:
  Job1:
    runs-on: ubuntu-latest
    name: Scan beta.glsauto.com
    steps:
      - name: scan beta.glsauto.com
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://beta.glsauto.com'
          rules_file_name: '.zap/beta.glsauto.com.zaproxy.rules.tsv'

  Job2:
    runs-on: ubuntu-latest
    name: Scan stg.fuel.glsauto.com
    steps:
      - name: scan stg.fuel.glsauto.com
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://stg.fuel.glsauto.com/'
          rules_file_name: '.zap/stg.fuel.glsauto.com.zaproxy.rules.tsv'

  Job3:
    runs-on: ubuntu-latest
    name: Scan stg-cat.app.glsauto.com
    steps:
      - name: scan stg-cat.app.glsauto.com
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://stg-cat.app.glsauto.com/'
  



