name: ZAP-Scan
run-name: Let's Go 🚀
on: 
  schedule:
  - cron:  '0 0 * * 6'

jobs:
  Zap-Scan:
    runs-on: ubuntu-latest
    name: Scan the web apps
    steps:
      - name: ZAP-Scan 1
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://beta.glsauto.com'

