name: Security Scan - OWASP ZAP ⚡     # More info = https://www.zaproxy.org/docs/docker/baseline-scan/
run-name: Zapoxy Scan /#${{ github.run_number }}
on: 
  workflow_dispatch:              # Enables manual run option
  schedule:
  - cron:  '0 4 * * 0'            # Sunday at 4AM

jobs:
  Job1:
    env: 
      website_name: beta.glsauto.com
      target_url: https://beta.glsauto.com   
    runs-on: ubuntu-latest
    name: Scan ${{ env.website_name }}
    steps: 
      - name: scan ${{ env.website_name }}
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: '${{ env.target_url }}'
          rules_file_name: '.zap/beta.${{ env.website_name }}_rules.tsv'  # make sure file has this naming convention

  Job2:
    runs-on: ubuntu-latest
    name: Scan web app
    steps:
      - name: scan stg.fuel.glsauto.com
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://stg.fuel.glsauto.com/'
          rules_file_name: '.zap/stg.fuel.glsauto.com_zaproxy_rules.tsv'

  Job3:
    runs-on: ubuntu-latest
    name: Scan web app
    steps:
      - name: scan stg.fuel.glsauto.com
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://stg-cat.app.glsauto.com/'

  



