name: Security Scan - OWASP ZAP ⚡     # More info = https://www.zaproxy.org/docs/docker/baseline-scan/
run-name: 'Zapoxy Scan #${{ github.run_number }}'
on: 
  workflow_dispatch:              # Enables manual run option
  schedule:
  - cron:  '0 4 * * 0'            # Sunday at 4AM

env:
  website-1: beta.glsauto.com
  website-2: stg.fuel.glsauto.com
  website-3: stg-cat.app.glsauto.com

jobs:
  website-1:
    runs-on: ubuntu-latest
    name: 'scan $website-1'
    steps:
      - name: 'scan $website-1'
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://${{ website-1 }}'
          rules_file_name: '.zap/beta.${{ website-1 }}_rules.tsv'

  Job2:
    runs-on: ubuntu-latest
    name: Scan web app
    steps:
      - name: scan stg.fuel.glsauto.com
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://stg.fuel.glsauto.com/'
          rules_file_name: '.zap/stg.fuel.glsauto.com_zaproxy_rules.tsv'

  Job3:
    runs-on: ubuntu-latest
    name: Scan web app
    steps:
      - name: scan stg.fuel.glsauto.com
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://stg-cat.app.glsauto.com/'

  



